apiVersion: apps/v1
kind: Deployment
metadata:
  name: trinity-apis
  namespace: trinity-apis
  labels:
    app: trinity-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trinity-apis
  strategy: {}
  template:
    metadata:
      labels:
        app: trinity-apis
    spec:
      containers:
      - name: trinity-apis
        image: trinity
        ports:
          - containerPort: 8080
        resources: {}