apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sample-trinity
  namespace: aws-sample-trinity
  labels:
    app: aws-sample-trinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sample-trinity
  strategy: {}
  template:
    metadata:
      labels:
        app: aws-sample-trinity
    spec:
      containers:
      - name: aws-sample-trinity
           # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        # image: REGISTRY/REPO:TAG
        # The full image will be dynamically added by Kustomize in the workflow.
        image: trinity-ecr
        ports:
          - containerPort: 5000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m