apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sample-trinity
  namespace: aws-sample-trinity
  labels:
    app: aws-sample-trinity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sample-trinity
  strategy: {}
  template:
    metadata:
      labels:
        app: aws-sample-trinity
    spec:
      containers:
      - name: aws-sample-trinity
        image: REGISTRY/IMAGE:TAG
        ports:
          - containerPort: 8080
        resources: {}