apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trinity-apis
  namespace: trinity-apis
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: trinity-apis
              servicePort: 80