apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aws-sample-trinity
  namespace: aws-sample-trinity
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: aws-sample-trinity
              servicePort: 80