apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "trinity-apis-ingress"
  namespace: "trinity-apis"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: trinity-apis-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "trinity-apis"
              servicePort: 80