kind: Service
apiVersion: v1
metadata:
  name: aws-sample-trinity
  namespace: aws-sample-trinity
spec:
  selector:
    app: aws-sample-trinity
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000