kind: Service
apiVersion: v1
metadata:
  name: trinity-apis
  namespace: trinity-apis
spec:
  selector:
    app: trinity-apis
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000